// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.Capability in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Capability contains the container capabilities to add or drop
 */
class Capability(
  add_capabilities: List<String> = emptyList(),
  drop_capabilities: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<Capability, Nothing>(ADAPTER, unknownFields) {
  /**
   * List of capabilities to add.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "addCapabilities"
  )
  val add_capabilities: List<String> = immutableCopyOf("add_capabilities", add_capabilities)

  /**
   * List of capabilities to drop.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "dropCapabilities"
  )
  val drop_capabilities: List<String> = immutableCopyOf("drop_capabilities", drop_capabilities)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Capability) return false
    if (unknownFields != other.unknownFields) return false
    if (add_capabilities != other.add_capabilities) return false
    if (drop_capabilities != other.drop_capabilities) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + add_capabilities.hashCode()
      result = result * 37 + drop_capabilities.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (add_capabilities.isNotEmpty()) result +=
        """add_capabilities=${sanitize(add_capabilities)}"""
    if (drop_capabilities.isNotEmpty()) result +=
        """drop_capabilities=${sanitize(drop_capabilities)}"""
    return result.joinToString(prefix = "Capability{", separator = ", ", postfix = "}")
  }

  fun copy(
    add_capabilities: List<String> = this.add_capabilities,
    drop_capabilities: List<String> = this.drop_capabilities,
    unknownFields: ByteString = this.unknownFields
  ): Capability = Capability(add_capabilities, drop_capabilities, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Capability> = object : ProtoAdapter<Capability>(
      FieldEncoding.LENGTH_DELIMITED, 
      Capability::class, 
      "type.googleapis.com/runtime.v1alpha2.Capability", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: Capability): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.add_capabilities)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.drop_capabilities)
        return size
      }

      override fun encode(writer: ProtoWriter, value: Capability) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.add_capabilities)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.drop_capabilities)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): Capability {
        val add_capabilities = mutableListOf<String>()
        val drop_capabilities = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> add_capabilities.add(ProtoAdapter.STRING.decode(reader))
            2 -> drop_capabilities.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return Capability(
          add_capabilities = add_capabilities,
          drop_capabilities = drop_capabilities,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: Capability): Capability = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
