// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.ContainerAttributes in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.Map
import kotlin.hashCode
import kotlin.jvm.JvmField
import kotlin.lazy
import okio.ByteString

/**
 * ContainerAttributes provides basic information of the container.
 */
class ContainerAttributes(
  /**
   * ID of the container.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val id: String = "",
  /**
   * Metadata of the container.
   */
  @field:WireField(
    tag = 2,
    adapter = "runtime.v1alpha2.ContainerMetadata#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val metadata: ContainerMetadata? = null,
  labels: Map<String, String> = emptyMap(),
  annotations: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ContainerAttributes, Nothing>(ADAPTER, unknownFields) {
  /**
   * Key-value pairs that may be used to scope and select individual resources.
   */
  @field:WireField(
    tag = 3,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val labels: Map<String, String> = immutableCopyOf("labels", labels)

  /**
   * Unstructured key-value map holding arbitrary metadata.
   * Annotations MUST NOT be altered by the runtime; the value of this field
   * MUST be identical to that of the corresponding ContainerConfig used to
   * instantiate the Container this status represents.
   */
  @field:WireField(
    tag = 4,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val annotations: Map<String, String> = immutableCopyOf("annotations", annotations)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ContainerAttributes) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (metadata != other.metadata) return false
    if (labels != other.labels) return false
    if (annotations != other.annotations) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + metadata.hashCode()
      result = result * 37 + labels.hashCode()
      result = result * 37 + annotations.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    if (metadata != null) result += """metadata=$metadata"""
    if (labels.isNotEmpty()) result += """labels=$labels"""
    if (annotations.isNotEmpty()) result += """annotations=$annotations"""
    return result.joinToString(prefix = "ContainerAttributes{", separator = ", ", postfix = "}")
  }

  fun copy(
    id: String = this.id,
    metadata: ContainerMetadata? = this.metadata,
    labels: Map<String, String> = this.labels,
    annotations: Map<String, String> = this.annotations,
    unknownFields: ByteString = this.unknownFields
  ): ContainerAttributes = ContainerAttributes(id, metadata, labels, annotations, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ContainerAttributes> = object : ProtoAdapter<ContainerAttributes>(
      FieldEncoding.LENGTH_DELIMITED, 
      ContainerAttributes::class, 
      "type.googleapis.com/runtime.v1alpha2.ContainerAttributes", 
      PROTO_3, 
      null
    ) {
      private val labelsAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      private val annotationsAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(value: ContainerAttributes): Int {
        var size = value.unknownFields.size
        if (value.id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        if (value.metadata != null) size += ContainerMetadata.ADAPTER.encodedSizeWithTag(2,
            value.metadata)
        size += labelsAdapter.encodedSizeWithTag(3, value.labels)
        size += annotationsAdapter.encodedSizeWithTag(4, value.annotations)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ContainerAttributes) {
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        if (value.metadata != null) ContainerMetadata.ADAPTER.encodeWithTag(writer, 2,
            value.metadata)
        labelsAdapter.encodeWithTag(writer, 3, value.labels)
        annotationsAdapter.encodeWithTag(writer, 4, value.annotations)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ContainerAttributes {
        var id: String = ""
        var metadata: ContainerMetadata? = null
        val labels = mutableMapOf<String, String>()
        val annotations = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> metadata = ContainerMetadata.ADAPTER.decode(reader)
            3 -> labels.putAll(labelsAdapter.decode(reader))
            4 -> annotations.putAll(annotationsAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ContainerAttributes(
          id = id,
          metadata = metadata,
          labels = labels,
          annotations = annotations,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ContainerAttributes): ContainerAttributes = value.copy(
        metadata = value.metadata?.let(ContainerMetadata.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
