// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.CreateContainerRequest in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class CreateContainerRequest(
  /**
   * ID of the PodSandbox in which the container should be created.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "podSandboxId"
  )
  val pod_sandbox_id: String = "",
  /**
   * Config of the container.
   */
  @field:WireField(
    tag = 2,
    adapter = "runtime.v1alpha2.ContainerConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val config: ContainerConfig? = null,
  /**
   * Config of the PodSandbox. This is the same config that was passed
   * to RunPodSandboxRequest to create the PodSandbox. It is passed again
   * here just for easy reference. The PodSandboxConfig is immutable and
   * remains the same throughout the lifetime of the pod.
   */
  @field:WireField(
    tag = 3,
    adapter = "runtime.v1alpha2.PodSandboxConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sandboxConfig"
  )
  val sandbox_config: PodSandboxConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CreateContainerRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CreateContainerRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (pod_sandbox_id != other.pod_sandbox_id) return false
    if (config != other.config) return false
    if (sandbox_config != other.sandbox_config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + pod_sandbox_id.hashCode()
      result = result * 37 + config.hashCode()
      result = result * 37 + sandbox_config.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """pod_sandbox_id=${sanitize(pod_sandbox_id)}"""
    if (config != null) result += """config=$config"""
    if (sandbox_config != null) result += """sandbox_config=$sandbox_config"""
    return result.joinToString(prefix = "CreateContainerRequest{", separator = ", ", postfix = "}")
  }

  fun copy(
    pod_sandbox_id: String = this.pod_sandbox_id,
    config: ContainerConfig? = this.config,
    sandbox_config: PodSandboxConfig? = this.sandbox_config,
    unknownFields: ByteString = this.unknownFields
  ): CreateContainerRequest = CreateContainerRequest(pod_sandbox_id, config, sandbox_config,
      unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<CreateContainerRequest> = object :
        ProtoAdapter<CreateContainerRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      CreateContainerRequest::class, 
      "type.googleapis.com/runtime.v1alpha2.CreateContainerRequest", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: CreateContainerRequest): Int {
        var size = value.unknownFields.size
        if (value.pod_sandbox_id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.pod_sandbox_id)
        if (value.config != null) size += ContainerConfig.ADAPTER.encodedSizeWithTag(2,
            value.config)
        if (value.sandbox_config != null) size += PodSandboxConfig.ADAPTER.encodedSizeWithTag(3,
            value.sandbox_config)
        return size
      }

      override fun encode(writer: ProtoWriter, value: CreateContainerRequest) {
        if (value.pod_sandbox_id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.pod_sandbox_id)
        if (value.config != null) ContainerConfig.ADAPTER.encodeWithTag(writer, 2, value.config)
        if (value.sandbox_config != null) PodSandboxConfig.ADAPTER.encodeWithTag(writer, 3,
            value.sandbox_config)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CreateContainerRequest {
        var pod_sandbox_id: String = ""
        var config: ContainerConfig? = null
        var sandbox_config: PodSandboxConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> pod_sandbox_id = ProtoAdapter.STRING.decode(reader)
            2 -> config = ContainerConfig.ADAPTER.decode(reader)
            3 -> sandbox_config = PodSandboxConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CreateContainerRequest(
          pod_sandbox_id = pod_sandbox_id,
          config = config,
          sandbox_config = sandbox_config,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: CreateContainerRequest): CreateContainerRequest = value.copy(
        config = value.config?.let(ContainerConfig.ADAPTER::redact),
        sandbox_config = value.sandbox_config?.let(PodSandboxConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
