// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.DNSConfig in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * DNSConfig specifies the DNS servers and search domains of a sandbox.
 */
class DNSConfig(
  servers: List<String> = emptyList(),
  searches: List<String> = emptyList(),
  options: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<DNSConfig, Nothing>(ADAPTER, unknownFields) {
  /**
   * List of DNS servers of the cluster.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val servers: List<String> = immutableCopyOf("servers", servers)

  /**
   * List of DNS search domains of the cluster.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val searches: List<String> = immutableCopyOf("searches", searches)

  /**
   * List of DNS options. See https://linux.die.net/man/5/resolv.conf
   * for all available options.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val options: List<String> = immutableCopyOf("options", options)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DNSConfig) return false
    if (unknownFields != other.unknownFields) return false
    if (servers != other.servers) return false
    if (searches != other.searches) return false
    if (options != other.options) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + servers.hashCode()
      result = result * 37 + searches.hashCode()
      result = result * 37 + options.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (servers.isNotEmpty()) result += """servers=${sanitize(servers)}"""
    if (searches.isNotEmpty()) result += """searches=${sanitize(searches)}"""
    if (options.isNotEmpty()) result += """options=${sanitize(options)}"""
    return result.joinToString(prefix = "DNSConfig{", separator = ", ", postfix = "}")
  }

  fun copy(
    servers: List<String> = this.servers,
    searches: List<String> = this.searches,
    options: List<String> = this.options,
    unknownFields: ByteString = this.unknownFields
  ): DNSConfig = DNSConfig(servers, searches, options, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<DNSConfig> = object : ProtoAdapter<DNSConfig>(
      FieldEncoding.LENGTH_DELIMITED, 
      DNSConfig::class, 
      "type.googleapis.com/runtime.v1alpha2.DNSConfig", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: DNSConfig): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.servers)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.searches)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.options)
        return size
      }

      override fun encode(writer: ProtoWriter, value: DNSConfig) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.servers)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.searches)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.options)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): DNSConfig {
        val servers = mutableListOf<String>()
        val searches = mutableListOf<String>()
        val options = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> servers.add(ProtoAdapter.STRING.decode(reader))
            2 -> searches.add(ProtoAdapter.STRING.decode(reader))
            3 -> options.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return DNSConfig(
          servers = servers,
          searches = searches,
          options = options,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: DNSConfig): DNSConfig = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
