// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.FilesystemIdentifier in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * FilesystemIdentifier uniquely identify the filesystem.
 */
class FilesystemIdentifier(
  /**
   * Mountpoint of a filesystem.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val mountpoint: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<FilesystemIdentifier, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FilesystemIdentifier) return false
    if (unknownFields != other.unknownFields) return false
    if (mountpoint != other.mountpoint) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + mountpoint.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """mountpoint=${sanitize(mountpoint)}"""
    return result.joinToString(prefix = "FilesystemIdentifier{", separator = ", ", postfix = "}")
  }

  fun copy(mountpoint: String = this.mountpoint, unknownFields: ByteString = this.unknownFields):
      FilesystemIdentifier = FilesystemIdentifier(mountpoint, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<FilesystemIdentifier> = object : ProtoAdapter<FilesystemIdentifier>(
      FieldEncoding.LENGTH_DELIMITED, 
      FilesystemIdentifier::class, 
      "type.googleapis.com/runtime.v1alpha2.FilesystemIdentifier", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: FilesystemIdentifier): Int {
        var size = value.unknownFields.size
        if (value.mountpoint != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.mountpoint)
        return size
      }

      override fun encode(writer: ProtoWriter, value: FilesystemIdentifier) {
        if (value.mountpoint != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.mountpoint)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): FilesystemIdentifier {
        var mountpoint: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> mountpoint = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return FilesystemIdentifier(
          mountpoint = mountpoint,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: FilesystemIdentifier): FilesystemIdentifier = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
