// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.ImageSpec in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.Map
import kotlin.hashCode
import kotlin.jvm.JvmField
import kotlin.lazy
import okio.ByteString

/**
 * ImageSpec is an internal representation of an image.
 */
class ImageSpec(
  /**
   * Container's Image field (e.g. imageID or imageDigest).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val image: String = "",
  annotations: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ImageSpec, Nothing>(ADAPTER, unknownFields) {
  /**
   * Unstructured key-value map holding arbitrary metadata.
   * ImageSpec Annotations can be used to help the runtime target specific
   * images in multi-arch images.
   */
  @field:WireField(
    tag = 2,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val annotations: Map<String, String> = immutableCopyOf("annotations", annotations)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ImageSpec) return false
    if (unknownFields != other.unknownFields) return false
    if (image != other.image) return false
    if (annotations != other.annotations) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + image.hashCode()
      result = result * 37 + annotations.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """image=${sanitize(image)}"""
    if (annotations.isNotEmpty()) result += """annotations=$annotations"""
    return result.joinToString(prefix = "ImageSpec{", separator = ", ", postfix = "}")
  }

  fun copy(
    image: String = this.image,
    annotations: Map<String, String> = this.annotations,
    unknownFields: ByteString = this.unknownFields
  ): ImageSpec = ImageSpec(image, annotations, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ImageSpec> = object : ProtoAdapter<ImageSpec>(
      FieldEncoding.LENGTH_DELIMITED, 
      ImageSpec::class, 
      "type.googleapis.com/runtime.v1alpha2.ImageSpec", 
      PROTO_3, 
      null
    ) {
      private val annotationsAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(value: ImageSpec): Int {
        var size = value.unknownFields.size
        if (value.image != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.image)
        size += annotationsAdapter.encodedSizeWithTag(2, value.annotations)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ImageSpec) {
        if (value.image != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.image)
        annotationsAdapter.encodeWithTag(writer, 2, value.annotations)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ImageSpec {
        var image: String = ""
        val annotations = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> image = ProtoAdapter.STRING.decode(reader)
            2 -> annotations.putAll(annotationsAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ImageSpec(
          image = image,
          annotations = annotations,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ImageSpec): ImageSpec = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
