// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.ImageFilter in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class ImageFilter(
  /**
   * Spec of the image.
   */
  @field:WireField(
    tag = 1,
    adapter = "runtime.v1alpha2.ImageSpec#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val image: ImageSpec? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ImageFilter, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ImageFilter) return false
    if (unknownFields != other.unknownFields) return false
    if (image != other.image) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + image.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (image != null) result += """image=$image"""
    return result.joinToString(prefix = "ImageFilter{", separator = ", ", postfix = "}")
  }

  fun copy(image: ImageSpec? = this.image, unknownFields: ByteString = this.unknownFields):
      ImageFilter = ImageFilter(image, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ImageFilter> = object : ProtoAdapter<ImageFilter>(
      FieldEncoding.LENGTH_DELIMITED, 
      ImageFilter::class, 
      "type.googleapis.com/runtime.v1alpha2.ImageFilter", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ImageFilter): Int {
        var size = value.unknownFields.size
        if (value.image != null) size += ImageSpec.ADAPTER.encodedSizeWithTag(1, value.image)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ImageFilter) {
        if (value.image != null) ImageSpec.ADAPTER.encodeWithTag(writer, 1, value.image)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ImageFilter {
        var image: ImageSpec? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> image = ImageSpec.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ImageFilter(
          image = image,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ImageFilter): ImageFilter = value.copy(
        image = value.image?.let(ImageSpec.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
