// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.ImageFsInfoResponse in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

class ImageFsInfoResponse(
  image_filesystems: List<FilesystemUsage> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ImageFsInfoResponse, Nothing>(ADAPTER, unknownFields) {
  /**
   * Information of image filesystem(s).
   */
  @field:WireField(
    tag = 1,
    adapter = "runtime.v1alpha2.FilesystemUsage#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "imageFilesystems"
  )
  val image_filesystems: List<FilesystemUsage> = immutableCopyOf("image_filesystems",
      image_filesystems)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ImageFsInfoResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (image_filesystems != other.image_filesystems) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + image_filesystems.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (image_filesystems.isNotEmpty()) result += """image_filesystems=$image_filesystems"""
    return result.joinToString(prefix = "ImageFsInfoResponse{", separator = ", ", postfix = "}")
  }

  fun copy(image_filesystems: List<FilesystemUsage> = this.image_filesystems,
      unknownFields: ByteString = this.unknownFields): ImageFsInfoResponse =
      ImageFsInfoResponse(image_filesystems, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ImageFsInfoResponse> = object : ProtoAdapter<ImageFsInfoResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ImageFsInfoResponse::class, 
      "type.googleapis.com/runtime.v1alpha2.ImageFsInfoResponse", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ImageFsInfoResponse): Int {
        var size = value.unknownFields.size
        size += FilesystemUsage.ADAPTER.asRepeated().encodedSizeWithTag(1, value.image_filesystems)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ImageFsInfoResponse) {
        FilesystemUsage.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.image_filesystems)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ImageFsInfoResponse {
        val image_filesystems = mutableListOf<FilesystemUsage>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> image_filesystems.add(FilesystemUsage.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ImageFsInfoResponse(
          image_filesystems = image_filesystems,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ImageFsInfoResponse): ImageFsInfoResponse = value.copy(
        image_filesystems = value.image_filesystems.redactElements(FilesystemUsage.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
