// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.KeyValue in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class KeyValue(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val key: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val value: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<KeyValue, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is KeyValue) return false
    if (unknownFields != other.unknownFields) return false
    if (key != other.key) return false
    if (value != other.value) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + key.hashCode()
      result = result * 37 + value.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """key=${sanitize(key)}"""
    result += """value=${sanitize(value)}"""
    return result.joinToString(prefix = "KeyValue{", separator = ", ", postfix = "}")
  }

  fun copy(
    key: String = this.key,
    value: String = this.value,
    unknownFields: ByteString = this.unknownFields
  ): KeyValue = KeyValue(key, value, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<KeyValue> = object : ProtoAdapter<KeyValue>(
      FieldEncoding.LENGTH_DELIMITED, 
      KeyValue::class, 
      "type.googleapis.com/runtime.v1alpha2.KeyValue", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: KeyValue): Int {
        var size = value.unknownFields.size
        if (value.key != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.key)
        if (value.value != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.value)
        return size
      }

      override fun encode(writer: ProtoWriter, value: KeyValue) {
        if (value.key != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.key)
        if (value.value != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.value)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): KeyValue {
        var key: String = ""
        var value: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> key = ProtoAdapter.STRING.decode(reader)
            2 -> value = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return KeyValue(
          key = key,
          value = value,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: KeyValue): KeyValue = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
