// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.ListContainersRequest in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class ListContainersRequest(
  @field:WireField(
    tag = 1,
    adapter = "runtime.v1alpha2.ContainerFilter#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val filter: ContainerFilter? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ListContainersRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ListContainersRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (filter != other.filter) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + filter.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (filter != null) result += """filter=$filter"""
    return result.joinToString(prefix = "ListContainersRequest{", separator = ", ", postfix = "}")
  }

  fun copy(filter: ContainerFilter? = this.filter, unknownFields: ByteString = this.unknownFields):
      ListContainersRequest = ListContainersRequest(filter, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ListContainersRequest> = object : ProtoAdapter<ListContainersRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      ListContainersRequest::class, 
      "type.googleapis.com/runtime.v1alpha2.ListContainersRequest", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ListContainersRequest): Int {
        var size = value.unknownFields.size
        if (value.filter != null) size += ContainerFilter.ADAPTER.encodedSizeWithTag(1,
            value.filter)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ListContainersRequest) {
        if (value.filter != null) ContainerFilter.ADAPTER.encodeWithTag(writer, 1, value.filter)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ListContainersRequest {
        var filter: ContainerFilter? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> filter = ContainerFilter.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ListContainersRequest(
          filter = filter,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ListContainersRequest): ListContainersRequest = value.copy(
        filter = value.filter?.let(ContainerFilter.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
