// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.MountPropagation in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

enum class MountPropagation(
  override val value: Int
) : WireEnum {
  /**
   * No mount propagation ("private" in Linux terminology).
   */
  PROPAGATION_PRIVATE(0),

  /**
   * Mounts get propagated from the host to the container ("rslave" in Linux).
   */
  PROPAGATION_HOST_TO_CONTAINER(1),

  /**
   * Mounts get propagated from the host to the container and from the
   * container to the host ("rshared" in Linux).
   */
  PROPAGATION_BIDIRECTIONAL(2);

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<MountPropagation> = object : EnumAdapter<MountPropagation>(
      MountPropagation::class, 
      PROTO_3, 
      MountPropagation.PROPAGATION_PRIVATE
    ) {
      override fun fromValue(value: Int): MountPropagation? = MountPropagation.fromValue(value)
    }

    @JvmStatic
    fun fromValue(value: Int): MountPropagation? = when (value) {
      0 -> PROPAGATION_PRIVATE
      1 -> PROPAGATION_HOST_TO_CONTAINER
      2 -> PROPAGATION_BIDIRECTIONAL
      else -> null
    }
  }
}
