// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.PodIP in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * PodIP represents an ip of a Pod
 */
class PodIP(
  /**
   * an ip is a string representation of an IPv4 or an IPv6
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val ip: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<PodIP, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PodIP) return false
    if (unknownFields != other.unknownFields) return false
    if (ip != other.ip) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + ip.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """ip=${sanitize(ip)}"""
    return result.joinToString(prefix = "PodIP{", separator = ", ", postfix = "}")
  }

  fun copy(ip: String = this.ip, unknownFields: ByteString = this.unknownFields): PodIP = PodIP(ip,
      unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<PodIP> = object : ProtoAdapter<PodIP>(
      FieldEncoding.LENGTH_DELIMITED, 
      PodIP::class, 
      "type.googleapis.com/runtime.v1alpha2.PodIP", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: PodIP): Int {
        var size = value.unknownFields.size
        if (value.ip != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.ip)
        return size
      }

      override fun encode(writer: ProtoWriter, value: PodIP) {
        if (value.ip != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ip)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): PodIP {
        var ip: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> ip = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PodIP(
          ip = ip,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: PodIP): PodIP = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
