// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.PodSandboxStateValue in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * PodSandboxStateValue is the wrapper of PodSandboxState.
 */
class PodSandboxStateValue(
  /**
   * State of the sandbox.
   */
  @field:WireField(
    tag = 1,
    adapter = "runtime.v1alpha2.PodSandboxState#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val state: PodSandboxState = PodSandboxState.SANDBOX_READY,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<PodSandboxStateValue, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PodSandboxStateValue) return false
    if (unknownFields != other.unknownFields) return false
    if (state != other.state) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + state.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """state=$state"""
    return result.joinToString(prefix = "PodSandboxStateValue{", separator = ", ", postfix = "}")
  }

  fun copy(state: PodSandboxState = this.state, unknownFields: ByteString = this.unknownFields):
      PodSandboxStateValue = PodSandboxStateValue(state, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<PodSandboxStateValue> = object : ProtoAdapter<PodSandboxStateValue>(
      FieldEncoding.LENGTH_DELIMITED, 
      PodSandboxStateValue::class, 
      "type.googleapis.com/runtime.v1alpha2.PodSandboxStateValue", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: PodSandboxStateValue): Int {
        var size = value.unknownFields.size
        if (value.state != PodSandboxState.SANDBOX_READY) size +=
            PodSandboxState.ADAPTER.encodedSizeWithTag(1, value.state)
        return size
      }

      override fun encode(writer: ProtoWriter, value: PodSandboxStateValue) {
        if (value.state != PodSandboxState.SANDBOX_READY)
            PodSandboxState.ADAPTER.encodeWithTag(writer, 1, value.state)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): PodSandboxStateValue {
        var state: PodSandboxState = PodSandboxState.SANDBOX_READY
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              state = PodSandboxState.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return PodSandboxStateValue(
          state = state,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: PodSandboxStateValue): PodSandboxStateValue = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
