// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.PodSandboxNetworkStatus in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.redactElements
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * PodSandboxNetworkStatus is the status of the network for a PodSandbox.
 */
class PodSandboxNetworkStatus(
  /**
   * IP address of the PodSandbox.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val ip: String = "",
  additional_ips: List<PodIP> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<PodSandboxNetworkStatus, Nothing>(ADAPTER, unknownFields) {
  /**
   * list of additional ips (not inclusive of PodSandboxNetworkStatus.Ip) of the
   * PodSandBoxNetworkStatus
   */
  @field:WireField(
    tag = 2,
    adapter = "runtime.v1alpha2.PodIP#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "additionalIps"
  )
  val additional_ips: List<PodIP> = immutableCopyOf("additional_ips", additional_ips)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PodSandboxNetworkStatus) return false
    if (unknownFields != other.unknownFields) return false
    if (ip != other.ip) return false
    if (additional_ips != other.additional_ips) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + ip.hashCode()
      result = result * 37 + additional_ips.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """ip=${sanitize(ip)}"""
    if (additional_ips.isNotEmpty()) result += """additional_ips=$additional_ips"""
    return result.joinToString(prefix = "PodSandboxNetworkStatus{", separator = ", ", postfix = "}")
  }

  fun copy(
    ip: String = this.ip,
    additional_ips: List<PodIP> = this.additional_ips,
    unknownFields: ByteString = this.unknownFields
  ): PodSandboxNetworkStatus = PodSandboxNetworkStatus(ip, additional_ips, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<PodSandboxNetworkStatus> = object :
        ProtoAdapter<PodSandboxNetworkStatus>(
      FieldEncoding.LENGTH_DELIMITED, 
      PodSandboxNetworkStatus::class, 
      "type.googleapis.com/runtime.v1alpha2.PodSandboxNetworkStatus", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: PodSandboxNetworkStatus): Int {
        var size = value.unknownFields.size
        if (value.ip != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.ip)
        size += PodIP.ADAPTER.asRepeated().encodedSizeWithTag(2, value.additional_ips)
        return size
      }

      override fun encode(writer: ProtoWriter, value: PodSandboxNetworkStatus) {
        if (value.ip != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ip)
        PodIP.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.additional_ips)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): PodSandboxNetworkStatus {
        var ip: String = ""
        val additional_ips = mutableListOf<PodIP>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> ip = ProtoAdapter.STRING.decode(reader)
            2 -> additional_ips.add(PodIP.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return PodSandboxNetworkStatus(
          ip = ip,
          additional_ips = additional_ips,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: PodSandboxNetworkStatus): PodSandboxNetworkStatus = value.copy(
        additional_ips = value.additional_ips.redactElements(PodIP.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
