// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.PodSandboxFilter in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.Map
import kotlin.hashCode
import kotlin.jvm.JvmField
import kotlin.lazy
import okio.ByteString

/**
 * PodSandboxFilter is used to filter a list of PodSandboxes.
 * All those fields are combined with 'AND'
 */
class PodSandboxFilter(
  /**
   * ID of the sandbox.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val id: String = "",
  /**
   * State of the sandbox.
   */
  @field:WireField(
    tag = 2,
    adapter = "runtime.v1alpha2.PodSandboxStateValue#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val state: PodSandboxStateValue? = null,
  label_selector: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<PodSandboxFilter, Nothing>(ADAPTER, unknownFields) {
  /**
   * LabelSelector to select matches.
   * Only api.MatchLabels is supported for now and the requirements
   * are ANDed. MatchExpressions is not supported yet.
   */
  @field:WireField(
    tag = 3,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "labelSelector"
  )
  val label_selector: Map<String, String> = immutableCopyOf("label_selector", label_selector)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PodSandboxFilter) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (state != other.state) return false
    if (label_selector != other.label_selector) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + state.hashCode()
      result = result * 37 + label_selector.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    if (state != null) result += """state=$state"""
    if (label_selector.isNotEmpty()) result += """label_selector=$label_selector"""
    return result.joinToString(prefix = "PodSandboxFilter{", separator = ", ", postfix = "}")
  }

  fun copy(
    id: String = this.id,
    state: PodSandboxStateValue? = this.state,
    label_selector: Map<String, String> = this.label_selector,
    unknownFields: ByteString = this.unknownFields
  ): PodSandboxFilter = PodSandboxFilter(id, state, label_selector, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<PodSandboxFilter> = object : ProtoAdapter<PodSandboxFilter>(
      FieldEncoding.LENGTH_DELIMITED, 
      PodSandboxFilter::class, 
      "type.googleapis.com/runtime.v1alpha2.PodSandboxFilter", 
      PROTO_3, 
      null
    ) {
      private val label_selectorAdapter: ProtoAdapter<Map<String, String>> by lazy {
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(value: PodSandboxFilter): Int {
        var size = value.unknownFields.size
        if (value.id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        if (value.state != null) size += PodSandboxStateValue.ADAPTER.encodedSizeWithTag(2,
            value.state)
        size += label_selectorAdapter.encodedSizeWithTag(3, value.label_selector)
        return size
      }

      override fun encode(writer: ProtoWriter, value: PodSandboxFilter) {
        if (value.id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        if (value.state != null) PodSandboxStateValue.ADAPTER.encodeWithTag(writer, 2, value.state)
        label_selectorAdapter.encodeWithTag(writer, 3, value.label_selector)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): PodSandboxFilter {
        var id: String = ""
        var state: PodSandboxStateValue? = null
        val label_selector = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> state = PodSandboxStateValue.ADAPTER.decode(reader)
            3 -> label_selector.putAll(label_selectorAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return PodSandboxFilter(
          id = id,
          state = state,
          label_selector = label_selector,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: PodSandboxFilter): PodSandboxFilter = value.copy(
        state = value.state?.let(PodSandboxStateValue.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
