// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.PullImageRequest in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class PullImageRequest(
  /**
   * Spec of the image.
   */
  @field:WireField(
    tag = 1,
    adapter = "runtime.v1alpha2.ImageSpec#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val image: ImageSpec? = null,
  /**
   * Authentication configuration for pulling the image.
   */
  @field:WireField(
    tag = 2,
    adapter = "runtime.v1alpha2.AuthConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val auth: AuthConfig? = null,
  /**
   * Config of the PodSandbox, which is used to pull image in PodSandbox context.
   */
  @field:WireField(
    tag = 3,
    adapter = "runtime.v1alpha2.PodSandboxConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sandboxConfig"
  )
  val sandbox_config: PodSandboxConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<PullImageRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PullImageRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (image != other.image) return false
    if (auth != other.auth) return false
    if (sandbox_config != other.sandbox_config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + image.hashCode()
      result = result * 37 + auth.hashCode()
      result = result * 37 + sandbox_config.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (image != null) result += """image=$image"""
    if (auth != null) result += """auth=$auth"""
    if (sandbox_config != null) result += """sandbox_config=$sandbox_config"""
    return result.joinToString(prefix = "PullImageRequest{", separator = ", ", postfix = "}")
  }

  fun copy(
    image: ImageSpec? = this.image,
    auth: AuthConfig? = this.auth,
    sandbox_config: PodSandboxConfig? = this.sandbox_config,
    unknownFields: ByteString = this.unknownFields
  ): PullImageRequest = PullImageRequest(image, auth, sandbox_config, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<PullImageRequest> = object : ProtoAdapter<PullImageRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      PullImageRequest::class, 
      "type.googleapis.com/runtime.v1alpha2.PullImageRequest", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: PullImageRequest): Int {
        var size = value.unknownFields.size
        if (value.image != null) size += ImageSpec.ADAPTER.encodedSizeWithTag(1, value.image)
        if (value.auth != null) size += AuthConfig.ADAPTER.encodedSizeWithTag(2, value.auth)
        if (value.sandbox_config != null) size += PodSandboxConfig.ADAPTER.encodedSizeWithTag(3,
            value.sandbox_config)
        return size
      }

      override fun encode(writer: ProtoWriter, value: PullImageRequest) {
        if (value.image != null) ImageSpec.ADAPTER.encodeWithTag(writer, 1, value.image)
        if (value.auth != null) AuthConfig.ADAPTER.encodeWithTag(writer, 2, value.auth)
        if (value.sandbox_config != null) PodSandboxConfig.ADAPTER.encodeWithTag(writer, 3,
            value.sandbox_config)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): PullImageRequest {
        var image: ImageSpec? = null
        var auth: AuthConfig? = null
        var sandbox_config: PodSandboxConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> image = ImageSpec.ADAPTER.decode(reader)
            2 -> auth = AuthConfig.ADAPTER.decode(reader)
            3 -> sandbox_config = PodSandboxConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PullImageRequest(
          image = image,
          auth = auth,
          sandbox_config = sandbox_config,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: PullImageRequest): PullImageRequest = value.copy(
        image = value.image?.let(ImageSpec.ADAPTER::redact),
        auth = value.auth?.let(AuthConfig.ADAPTER::redact),
        sandbox_config = value.sandbox_config?.let(PodSandboxConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
