// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.ReopenContainerLogResponse in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.jvm.JvmField
import okio.ByteString

class ReopenContainerLogResponse(
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ReopenContainerLogResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ReopenContainerLogResponse) return false
    if (unknownFields != other.unknownFields) return false
    return true
  }

  override fun hashCode(): Int = unknownFields.hashCode()

  override fun toString(): String = "ReopenContainerLogResponse{}"

  fun copy(unknownFields: ByteString = this.unknownFields): ReopenContainerLogResponse =
      ReopenContainerLogResponse(unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ReopenContainerLogResponse> = object :
        ProtoAdapter<ReopenContainerLogResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ReopenContainerLogResponse::class, 
      "type.googleapis.com/runtime.v1alpha2.ReopenContainerLogResponse", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ReopenContainerLogResponse): Int {
        var size = value.unknownFields.size
        return size
      }

      override fun encode(writer: ProtoWriter, value: ReopenContainerLogResponse) {
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ReopenContainerLogResponse {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return ReopenContainerLogResponse(
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ReopenContainerLogResponse): ReopenContainerLogResponse =
          value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
