// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.RuntimeStatus in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * RuntimeStatus is information about the current status of the runtime.
 */
class RuntimeStatus(
  conditions: List<RuntimeCondition> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<RuntimeStatus, Nothing>(ADAPTER, unknownFields) {
  /**
   * List of current observed runtime conditions.
   */
  @field:WireField(
    tag = 1,
    adapter = "runtime.v1alpha2.RuntimeCondition#ADAPTER",
    label = WireField.Label.REPEATED
  )
  val conditions: List<RuntimeCondition> = immutableCopyOf("conditions", conditions)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RuntimeStatus) return false
    if (unknownFields != other.unknownFields) return false
    if (conditions != other.conditions) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + conditions.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (conditions.isNotEmpty()) result += """conditions=$conditions"""
    return result.joinToString(prefix = "RuntimeStatus{", separator = ", ", postfix = "}")
  }

  fun copy(conditions: List<RuntimeCondition> = this.conditions, unknownFields: ByteString =
      this.unknownFields): RuntimeStatus = RuntimeStatus(conditions, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<RuntimeStatus> = object : ProtoAdapter<RuntimeStatus>(
      FieldEncoding.LENGTH_DELIMITED, 
      RuntimeStatus::class, 
      "type.googleapis.com/runtime.v1alpha2.RuntimeStatus", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: RuntimeStatus): Int {
        var size = value.unknownFields.size
        size += RuntimeCondition.ADAPTER.asRepeated().encodedSizeWithTag(1, value.conditions)
        return size
      }

      override fun encode(writer: ProtoWriter, value: RuntimeStatus) {
        RuntimeCondition.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.conditions)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): RuntimeStatus {
        val conditions = mutableListOf<RuntimeCondition>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> conditions.add(RuntimeCondition.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return RuntimeStatus(
          conditions = conditions,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: RuntimeStatus): RuntimeStatus = value.copy(
        conditions = value.conditions.redactElements(RuntimeCondition.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
