// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.RuntimeConfig in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class RuntimeConfig(
  @field:WireField(
    tag = 1,
    adapter = "runtime.v1alpha2.NetworkConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "networkConfig"
  )
  val network_config: NetworkConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<RuntimeConfig, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RuntimeConfig) return false
    if (unknownFields != other.unknownFields) return false
    if (network_config != other.network_config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + network_config.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (network_config != null) result += """network_config=$network_config"""
    return result.joinToString(prefix = "RuntimeConfig{", separator = ", ", postfix = "}")
  }

  fun copy(network_config: NetworkConfig? = this.network_config, unknownFields: ByteString =
      this.unknownFields): RuntimeConfig = RuntimeConfig(network_config, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<RuntimeConfig> = object : ProtoAdapter<RuntimeConfig>(
      FieldEncoding.LENGTH_DELIMITED, 
      RuntimeConfig::class, 
      "type.googleapis.com/runtime.v1alpha2.RuntimeConfig", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: RuntimeConfig): Int {
        var size = value.unknownFields.size
        if (value.network_config != null) size += NetworkConfig.ADAPTER.encodedSizeWithTag(1,
            value.network_config)
        return size
      }

      override fun encode(writer: ProtoWriter, value: RuntimeConfig) {
        if (value.network_config != null) NetworkConfig.ADAPTER.encodeWithTag(writer, 1,
            value.network_config)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): RuntimeConfig {
        var network_config: NetworkConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> network_config = NetworkConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RuntimeConfig(
          network_config = network_config,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: RuntimeConfig): RuntimeConfig = value.copy(
        network_config = value.network_config?.let(NetworkConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
