// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.StatusRequest in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class StatusRequest(
  /**
   * Verbose indicates whether to return extra information about the runtime.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY
  )
  val verbose: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<StatusRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StatusRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (verbose != other.verbose) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + verbose.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """verbose=$verbose"""
    return result.joinToString(prefix = "StatusRequest{", separator = ", ", postfix = "}")
  }

  fun copy(verbose: Boolean = this.verbose, unknownFields: ByteString = this.unknownFields):
      StatusRequest = StatusRequest(verbose, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<StatusRequest> = object : ProtoAdapter<StatusRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      StatusRequest::class, 
      "type.googleapis.com/runtime.v1alpha2.StatusRequest", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: StatusRequest): Int {
        var size = value.unknownFields.size
        if (value.verbose != false) size += ProtoAdapter.BOOL.encodedSizeWithTag(1, value.verbose)
        return size
      }

      override fun encode(writer: ProtoWriter, value: StatusRequest) {
        if (value.verbose != false) ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.verbose)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): StatusRequest {
        var verbose: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> verbose = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StatusRequest(
          verbose = verbose,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: StatusRequest): StatusRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
