// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.UpdateContainerResourcesRequest in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class UpdateContainerResourcesRequest(
  /**
   * ID of the container to update.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "containerId"
  )
  val container_id: String = "",
  /**
   * Resource configuration specific to Linux containers.
   */
  @field:WireField(
    tag = 2,
    adapter = "runtime.v1alpha2.LinuxContainerResources#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  val linux: LinuxContainerResources? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<UpdateContainerResourcesRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UpdateContainerResourcesRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (container_id != other.container_id) return false
    if (linux != other.linux) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + container_id.hashCode()
      result = result * 37 + linux.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """container_id=${sanitize(container_id)}"""
    if (linux != null) result += """linux=$linux"""
    return result.joinToString(prefix = "UpdateContainerResourcesRequest{", separator = ", ",
        postfix = "}")
  }

  fun copy(
    container_id: String = this.container_id,
    linux: LinuxContainerResources? = this.linux,
    unknownFields: ByteString = this.unknownFields
  ): UpdateContainerResourcesRequest = UpdateContainerResourcesRequest(container_id, linux,
      unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<UpdateContainerResourcesRequest> = object :
        ProtoAdapter<UpdateContainerResourcesRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      UpdateContainerResourcesRequest::class, 
      "type.googleapis.com/runtime.v1alpha2.UpdateContainerResourcesRequest", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: UpdateContainerResourcesRequest): Int {
        var size = value.unknownFields.size
        if (value.container_id != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.container_id)
        if (value.linux != null) size += LinuxContainerResources.ADAPTER.encodedSizeWithTag(2,
            value.linux)
        return size
      }

      override fun encode(writer: ProtoWriter, value: UpdateContainerResourcesRequest) {
        if (value.container_id != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.container_id)
        if (value.linux != null) LinuxContainerResources.ADAPTER.encodeWithTag(writer, 2,
            value.linux)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): UpdateContainerResourcesRequest {
        var container_id: String = ""
        var linux: LinuxContainerResources? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> container_id = ProtoAdapter.STRING.decode(reader)
            2 -> linux = LinuxContainerResources.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UpdateContainerResourcesRequest(
          container_id = container_id,
          linux = linux,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: UpdateContainerResourcesRequest): UpdateContainerResourcesRequest =
          value.copy(
        linux = value.linux?.let(LinuxContainerResources.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
