// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.UpdateRuntimeConfigRequest in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class UpdateRuntimeConfigRequest(
  @field:WireField(
    tag = 1,
    adapter = "runtime.v1alpha2.RuntimeConfig#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "runtimeConfig"
  )
  val runtime_config: RuntimeConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<UpdateRuntimeConfigRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UpdateRuntimeConfigRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (runtime_config != other.runtime_config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + runtime_config.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (runtime_config != null) result += """runtime_config=$runtime_config"""
    return result.joinToString(prefix = "UpdateRuntimeConfigRequest{", separator = ", ", postfix =
        "}")
  }

  fun copy(runtime_config: RuntimeConfig? = this.runtime_config, unknownFields: ByteString =
      this.unknownFields): UpdateRuntimeConfigRequest = UpdateRuntimeConfigRequest(runtime_config,
      unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<UpdateRuntimeConfigRequest> = object :
        ProtoAdapter<UpdateRuntimeConfigRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      UpdateRuntimeConfigRequest::class, 
      "type.googleapis.com/runtime.v1alpha2.UpdateRuntimeConfigRequest", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: UpdateRuntimeConfigRequest): Int {
        var size = value.unknownFields.size
        if (value.runtime_config != null) size += RuntimeConfig.ADAPTER.encodedSizeWithTag(1,
            value.runtime_config)
        return size
      }

      override fun encode(writer: ProtoWriter, value: UpdateRuntimeConfigRequest) {
        if (value.runtime_config != null) RuntimeConfig.ADAPTER.encodeWithTag(writer, 1,
            value.runtime_config)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): UpdateRuntimeConfigRequest {
        var runtime_config: RuntimeConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> runtime_config = RuntimeConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UpdateRuntimeConfigRequest(
          runtime_config = runtime_config,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: UpdateRuntimeConfigRequest): UpdateRuntimeConfigRequest =
          value.copy(
        runtime_config = value.runtime_config?.let(RuntimeConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
