// Code generated by Wire protocol buffer compiler, do not edit.
// Source: runtime.v1alpha2.VersionResponse in io/k8s/cri_api.proto
package runtime.v1alpha2

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class VersionResponse(
  /**
   * Version of the kubelet runtime API.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val version: String = "",
  /**
   * Name of the container runtime.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "runtimeName"
  )
  val runtime_name: String = "",
  /**
   * Version of the container runtime. The string must be
   * semver-compatible.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "runtimeVersion"
  )
  val runtime_version: String = "",
  /**
   * API version of the container runtime. The string must be
   * semver-compatible.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "runtimeApiVersion"
  )
  val runtime_api_version: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<VersionResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is VersionResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (version != other.version) return false
    if (runtime_name != other.runtime_name) return false
    if (runtime_version != other.runtime_version) return false
    if (runtime_api_version != other.runtime_api_version) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + version.hashCode()
      result = result * 37 + runtime_name.hashCode()
      result = result * 37 + runtime_version.hashCode()
      result = result * 37 + runtime_api_version.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """version=${sanitize(version)}"""
    result += """runtime_name=${sanitize(runtime_name)}"""
    result += """runtime_version=${sanitize(runtime_version)}"""
    result += """runtime_api_version=${sanitize(runtime_api_version)}"""
    return result.joinToString(prefix = "VersionResponse{", separator = ", ", postfix = "}")
  }

  fun copy(
    version: String = this.version,
    runtime_name: String = this.runtime_name,
    runtime_version: String = this.runtime_version,
    runtime_api_version: String = this.runtime_api_version,
    unknownFields: ByteString = this.unknownFields
  ): VersionResponse = VersionResponse(version, runtime_name, runtime_version, runtime_api_version,
      unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<VersionResponse> = object : ProtoAdapter<VersionResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      VersionResponse::class, 
      "type.googleapis.com/runtime.v1alpha2.VersionResponse", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: VersionResponse): Int {
        var size = value.unknownFields.size
        if (value.version != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.version)
        if (value.runtime_name != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2,
            value.runtime_name)
        if (value.runtime_version != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3,
            value.runtime_version)
        if (value.runtime_api_version != "") size += ProtoAdapter.STRING.encodedSizeWithTag(4,
            value.runtime_api_version)
        return size
      }

      override fun encode(writer: ProtoWriter, value: VersionResponse) {
        if (value.version != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.version)
        if (value.runtime_name != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.runtime_name)
        if (value.runtime_version != "") ProtoAdapter.STRING.encodeWithTag(writer, 3,
            value.runtime_version)
        if (value.runtime_api_version != "") ProtoAdapter.STRING.encodeWithTag(writer, 4,
            value.runtime_api_version)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): VersionResponse {
        var version: String = ""
        var runtime_name: String = ""
        var runtime_version: String = ""
        var runtime_api_version: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> version = ProtoAdapter.STRING.decode(reader)
            2 -> runtime_name = ProtoAdapter.STRING.decode(reader)
            3 -> runtime_version = ProtoAdapter.STRING.decode(reader)
            4 -> runtime_api_version = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return VersionResponse(
          version = version,
          runtime_name = runtime_name,
          runtime_version = runtime_version,
          runtime_api_version = runtime_api_version,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: VersionResponse): VersionResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
